-- ADVANCED QUESTIONS
-- 9) Calculate the stock remaining after fulfilling all orders

SELECT
	BOOKS.BOOK_ID,
	BOOKS.TITLE,
	BOOKS.STOCK,
	SUM(ORDERS.QUANTITY) AS TOTAL_SOLD,
	(BOOKS.STOCK - SUM(ORDERS.QUANTITY)) AS REMAINING_STOCK
FROM
	BOOKS
	JOIN ORDERS ON BOOKS.BOOK_ID = ORDERS.BOOK_ID
GROUP BY
	BOOKS.BOOK_ID,
	BOOKS.TITLE,
	BOOKS.STOCK
ORDER BY
	REMAINING_STOCK DESC;