-- ADAVANCE QUESTIONS
-- 3)List customers who have placed at least 2 orders
SELECT
	CUSTOMERS.CUSTOMER_ID,
	CUSTOMERS.NAME,
	COUNT(ORDERS.ORDER_ID) AS ORDER_COUNT
FROM
	CUSTOMERS
	JOIN ORDERS ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID
GROUP BY
	CUSTOMERS.CUSTOMER_ID,
	CUSTOMERS.NAME
HAVING
	COUNT(ORDERS.ORDER_ID) >= 2
ORDER BY
	ORDER_COUNT ASC;