--  ADAVANCE QUESTIONS
-- 4) Find the most frequently ordered book

SELECT
	BOOKS.TITLE,
	COUNT(ORDERS.ORDER_ID) AS ORDER_COUNT
FROM
	BOOKS
	JOIN ORDERS ON BOOKS.BOOK_ID = ORDERS.BOOK_ID
GROUP BY
	BOOKS.TITLE
ORDER BY
	ORDER_COUNT DESC
LIMIT
	1;