-- ADVANCE QUEATIONS
-- 6) Retrieve the total quantity of books sold by each author

SELECT
	BOOKS.AUTHOR,
	SUM(ORDERS.QUANTITY) AS TOTAL_QUANTITY
FROM
	BOOKS
	JOIN ORDERS ON BOOKS.BOOK_ID = ORDERS.BOOK_ID
GROUP BY
	BOOKS.AUTHOR
ORDER BY
	TOTAL_QUANTITY DESC;