-- 
-- 7) List the cities where customers who spent over $30 are located

SELECT DISTINCT
	CUSTOMERS.CITY,
	ORDERS.TOTAL_AMOUNT
FROM
	CUSTOMERS
	JOIN ORDERS ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID
WHERE
	ORDERS.TOTAL_AMOUNT > 30