-- ADVANCED QUESTIONS
-- 8) Find the customer who spent the most on orders

SELECT
	CUSTOMERS.NAME,
	SUM(ORDERS.TOTAL_AMOUNT) AS TOTAL_SPEND
FROM
	CUSTOMERS
	JOIN ORDERS ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID
GROUP BY
	CUSTOMERS.NAME
ORDER BY
	TOTAL_SPEND DESC
LIMIT
	1;