-- ADAVANCE QUESTIONS
-- 1) Retrieve the total number of books sold for each genre

SELECT
	BOOKS.GENRE,
	SUM(ORDERS.QUANTITY) AS TOTAL_BOOKS_SOLD
FROM
	BOOKS
	JOIN ORDERS ON BOOKS.BOOK_ID = ORDERS.BOOK_ID
GROUP BY
	BOOKS.GENRE
ORDER BY
	TOTAL_BOOKS_SOLD DESC;